### ISSUE TITLE
RequestHeaderParser causing server unusable when POST body exceeds 4096

### ISSUE THREAD

**Issue by halftan** [reactphp/http#87] opened 2017-01-06 08:08 UTC
The header size limits [here](https://github.com/reactphp/http/blob/master/src/RequestHeaderParser.php#L20), evaluates the entire HTTP request's size `strlen($data)` where `$data` contains everything read from Stream, whose `data` event emitted [here](https://github.com/reactphp/stream/blob/master/src/Stream.php#L170).

My solution is to change:

```php
        if (strlen($this->buffer) + strlen($data) > $this->maxSize) {
```

into:

```php
        @list($header,) = explode("\r\n\r\n", $data);
        if (strlen($this->buffer) + strlen($header) > $this->maxSize) {
```

If it's ok, then I'll submit a PR regarding this issue.

**Comment by clue** [comment] 2017-01-06 09:08
Looks like this is a duplicate of #80, see also #82 for a pending PR. This is currently in review, any input is welcome :+1:

**Closed by clue** 2017-01-06 09:08 UTC
