### ISSUE TITLE
Connection refused error

### ISSUE THREAD

**Issue by wolrd** [reactphp/http#337] opened 2019-03-21 07:42 UTC
Hello!

I can not send a command to external server. If I send it inside the local server, then it works correctly.

The port is open on an external server.

What could be the problem?

My code:
```
$loop = Factory::create();
        $connector = new Connector($loop);
        $connector
            ->connect(sprintf('%s:%s', '35.158.187.551', '9090'))
            ->then(
                function(ConnectionInterface $conn) use ($params)
                {
                    $messageBody = json_encode($params);

                    $conn->write($messageBody);
                    $conn->end();
                },
                function ($error)
                {
                    var_dump($error);
                    if (stripos($error, 'Connection refused') == false)
                        \Log::info($error);
                }
            );
        $loop->run();
```

My server:
```
$loop = Factory::create();
		$socket = new \React\Socket\Server(sprintf('%s:%s', $host, $port), $loop);
        $socket = new LimitingServer($socket, null);
       

		$socket->on('connection', function(ConnectionInterface $connection) use ($socket)
		{
		    $connection->on('data', function($data) use ($connection, $socket)
            {
...
            }
           });
});

		$loop->run();
```

Error:
```
object(RuntimeException)#502 (7) { ["message":protected]=> string(18) "Connection refused" ["string":"Exception":private]=> string(0) "" ["code":protected]=> int(0) ["file":protected]=> string(54) "/var/www/html/vendor/react/socket/src/TcpConnector.php" ["line":protected]=> int(110) ["trace":"Exception":private]=> array(71) { [0]=> array(4) { ["function"]=> string(22) "React\Socket\{closure}" ["class"]=> string(25) "React\Socket\TcpConnector" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> resource(466) of type (Unknown) [1]=> object(React\EventLoop\StreamSelectLoop)#458 (8) { ["nextTickQueue":"React\EventLoop\StreamSelectLoop":private]=> object(React\EventLoop\Tick\NextTickQueue)#453 (2) { ["eventLoop":"React\EventLoop\Tick\NextTickQueue":private]=> *RECURSION* 
...
```

**Comment by clue** [comment] 2019-03-21 09:41
I don't see anything specific to this HTTP library, closing as duplicate of https://github.com/reactphp/socket/issues/197.

**Closed by clue** 2019-03-21 09:41 UTC
Labels: question
