### ISSUE TITLE
EmptyBodyStream as request body not working

### ISSUE THREAD

**Issue by martin-heralecky** [reactphp/http#497] opened 2023-06-02 08:41 UTC
There seems to be a problem when attempting to pass `EmptyBodyStream` as body to HTTP requests:

```php
(new Browser())
    ->requestStreaming("GET", "https://stackoverflow.com", [], new \React\Http\Io\EmptyBodyStream())
    ->then(var_dump(...)); // never get's triggered
```

Whereas, empty resource works just fine:

```php
(new Browser())
    ->requestStreaming("GET", "https://stackoverflow.com", [], new ReadableResourceStream(tmpfile()))
    ->then(var_dump(...));
```

I have tried other servers (URLs) as well, and for some of them I get a response immediatelly, for some there is a 10s delay. Maybe the socket isn't being closed when using `EmptyBodyStream`?

---

The full example (reason I care) is that I though this would work as a simple HTTP proxy:

```php
$browser = new Browser();
$browser = $browser->withRejectErrorResponse(false);

$server = new HttpServer(
    new StreamingRequestMiddleware(),
    fn(ServerRequestInterface $req) => $browser
        ->requestStreaming($req->getMethod(), TARGET_URL, [], $req->getBody())
        ->then(fn(ResponseInterface $res) => new Response($res->getStatusCode(), [], $res->getBody())),
);
```

But it only works for requests with non-empty bodies. Otherwise `$req->getBody()` is `EmptyBodyStream` and the requests get stuck.

**Comment by SimonFrings** [comment] 2024-02-22 08:08
Hey @martin-heralecky, thanks for bringing this up :+1:

I talked with @clue about this, and it indeed seems to be a bug that has found its way into the project over the last few releases. We've already started working on a fix for this, so I will keep you updated as we make progress.

As you also may know, we're currently working on ReactPHP v3 and releasing the roadmap tickets for each component (see [reactphp/event-loop#271](https://github.com/reactphp/event-loop/issues/271) and others). The HTTP roadmap ticket will also be released soon, and to give you a sneak peek, we plan to release at least v1.10.0 before branching out with a 3.x branch. So, I think it makes sense to resolve this bug as part of the upcoming v1.1.0.0 and thus also for the upcoming v3.

**Comment by clue** [comment] 2024-02-22 14:52
@martin-heralecky Again thank you for reporting, that was a nasty one! I've just filed #516 which fixes the problem and introduces additional tests to avoid any future regressions.

I've double-checked your gist, and I'm happy to confirm that it now works flawlessly with the applied changes. The fix may actually look surprisingly simple, but analyzing the problem and coming up with this fix took a couple of hours. If you'd like to support this development, consider [sponsoring ReactPHP](https://github.com/sponsors/reactphp)! ❤️ Thank you!

**Closed as completed** 2024-02-26 10:09 UTC
Labels: bug

**Comment by martin-heralecky** [comment] 2024-02-28 12:25
Thanks a lot! I'll definitely consider sponsoring the project. You guys are doing an excelent job.
