### ISSUE TITLE
post request parameters

### ISSUE THREAD

**Issue by hemantjp** [reactphp/http#299] opened 2018-01-12 20:15 UTC
Hi,
i am unable to get post params using the Server object.`$request->getParsedBody()`returning null
i have to switch to streamingserver to do so.

i read through the previous discussions and but got lost.

an example on how get post parameters would be great.

**Comment by WyriHaximus** [comment] 2018-01-12 21:34
Hey @hemantjp,

That doesn't sound like it's working as intended. Have you checked out example [#12](https://github.com/reactphp/http/blob/master/examples/12-upload.php)? Can you share a gist of your server code so we can try locally for ourself?

**Comment by hemantjp** [comment] 2018-01-13 08:51
Sir,
From the example attached only i realised i should use `StreamingServer.`

i wanted to know if this functionality existed using the normal `Server` object.
since in the commits it is mentioned `Recommend Server by default instead of advanced StreamingServer`

the code i was using is copied from the example suggested.

**Comment by clue** [comment] 2018-01-13 11:24
@hemantjp Yes, both the `Server` and advanced `StreamingServer` can be used to access form field values and arbitrary POST values as documented in our README. I've just tried the example as pointed out by @WyriHaximus and also adapted this to use the `Server` class instead and everything seems to work as expected.

If you're "unable to get post params", please show us some code your having issues with. Thank you! 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2018-01-13 11:24 UTC
Labels: help wanted, question
