### ISSUE TITLE
Chunked encoder emits data before it is piped to connection

### ISSUE THREAD

**Issue by phpbg** [reactphp/http#332] opened 2019-01-23 21:02 UTC
In `StreamingServer::handleResponse()`:

    if ($chunked) {
        $body = new ChunkedEncoder($body);
    }
    //'data' events happen here
    ...
    $body->pipe($connection);

I have chunked encoding, but my $body starts emitting data (which get chunk encoded), but all of this **before** it is piped to $connection.

Shouldn't we call `pause()` on original $body before creating `ChunkedEncoder`, then resume after piping to connection?

**Comment by phpbg** [comment] 2019-01-23 21:21
in fact, data events can happen before ChuckedEncoder is created.
I'd like to create my $body in paused state, but i have no way to resume it or detect it can be resumed...

**Comment by clue** [comment] 2019-01-25 11:42
@phpbg Thanks for reporting!

I'm not sure I follow what the problem is here, perhaps you can gist this? It sounds like your problem might not be related to these internals and chunked encoding at all. If you want to return a [streaming response](https://github.com/reactphp/http#streaming-response), then you have to *first return* this response instance and then *afterwards* write to this stream. For example:


```php
$server = new Server(function (ServerRequestInterface $request) use ($loop) {
    $stream = new ThroughStream();

    // "initial" data has to be deferred to a future tick or timer
    $loop->futureTick(function () use ($stream) {
        $stream->write("hello!" . PHP_EOL);
    });

    $timer = $loop->addPeriodicTimer(0.5, function () use ($stream) {
        $stream->write(microtime(true) . PHP_EOL);
    });

    $loop->addTimer(5, function() use ($loop, $timer, $stream) {
        $loop->cancelTimer($timer);
        $stream->end();
    });

    return new Response(
        200,
        array(
            'Content-Type' => 'text/plain'
        ),
        $stream
    );
});
```

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2019-01-25 11:42 UTC
Labels: help wanted, question

**Comment by phpbg** [comment] 2019-01-25 19:46
@clue Thank you for your detailed example. `futureTick()` did the trick perfectly!
Regards!
